apiVersion: v1
kind: Secret
metadata:
  name: "ecr-registry-secret-demo"
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.ecrRegistrySecret.dockerConfigJson }}
